### ISSUE TITLE
alias_method_chain is deprecated

### ISSUE THREAD

**Issue by shaicoleman** [softace/utf8_enforcer_workaround#4]
With Rails 5 and Ruby 2.3 I'm getting the following warning

`DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super.`

**Comment by shaicoleman** [comment]
Pull request to fix: https://github.com/softace/utf8_enforcer_workaround/pull/5

**Comment by jarl-dk** [comment]
Thanks, merged.
